### ISSUE TITLE
bash_aliases for different users

### ISSUE THREAD

**Issue by MaxiReglisse** [igormukhingmailcom/ansible-role-bash_aliases#3]
How can i use ansible-role-bash_aliases to set bash_aliases to different users ?

And subsidiary question: how to endow them with specific aliases, different from each other ?

**Comment by igormukhingmailcom** [comment]
Something like this:

```yaml
# playbook.yml

vars:
    # See all available variables at defaults/main.yml
    bash_aliases_user1:
      - { alias: 'sf', command: 'php app/console' }
    bash_aliases_user2:
      - { alias: 'sfcc', command: 'sf cache:clear' }
      - { alias: 'sfccnw', command: 'sfcc --no-warmup' }
    bash_aliases_user3:
      - { alias: 'sfl', command: 'sf list' }
      - { alias: 'sflg', command: 'sf list | grep' }

roles:
  - role: igor_mukhin.bash_aliases
    bash_aliases: "{{ bash_aliases_user1 }}"
    bash_aliases_path: "/home/user1/.bash_aliases"
  - role: igor_mukhin.bash_aliases
    bash_aliases: "{{ bash_aliases_user2 }}"
    bash_aliases_path: "/home/user2/.bash_aliases"
  - role: igor_mukhin.bash_aliases
    bash_aliases: "{{ bash_aliases_user3 }}"
    bash_aliases_path: "/home/user3/.bash_aliases"
```
